server:
  port: 8999

spring:
  application:
    name: spring-ai-alibaba-zhipuai-chat-model-example

  ai:
    zhipuai:
      base-url: "https://open.bigmodel.cn/api/paas"
      api-key: 73269689f8d8e1e241d367472ab1ec3b.7rrVHkInLi8hQZv4