server:
  port: 8999

spring:
  application:
    name: spring-ai-alibaba-zhipuai-chat-model-example
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8091/ai_chat
    username: root
    password: yEPN{q1T}uVr4b68M=w.5jvX7!2?KkH9
  ai:
    zhipuai:
      base-url: "https://open.bigmodel.cn/api/paas"
      api-key: 73269689f8d8e1e241d367472ab1ec3b.7rrVHkInLi8hQZv4